version: '3.9'

services:
  aerospike-vector-search:
    image: aerospike/aerospike-vector-search:0.11.1
    container_name: "aerospike-vector-search"
    depends_on:
      aerospike-cluster:
        condition: service_healthy
    ports:
     - "5000:5000"
     - "5040:5040"
    volumes:
      - ${PWD}/volumes:/etc/aerospike-vector-search
    healthcheck:
      test: ["CMD", "curl", "-f", "http://aerospike-vector-search:5040/manage/rest/v1"]
      interval: 30s
      timeout: 20s
      retries: 3
  
  aerospike-cluster:
    image: aerospike/aerospike-server-enterprise:7.1.0.0
    container_name: "aerospike-cluster"
    command: --config-file /etc/aerospike/aerospike.conf
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
      - "3003:3003"
    volumes:
      - ${PWD}/volumes:/etc/aerospike
    healthcheck:
#      test: [ "CMD", "asinfo", "-U", "admin", "-P", "admin", "-p", "3000", "-v", "build" ]
      test: [ "CMD", "asinfo", "-p", "3000", "-v", "build" ]
      interval: 30s
      timeout: 20s
      retries: 3

  side-prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ${PWD}/volumes:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/side-prometheus.yml"
      - "--log.level=debug"  # Enable debug logging
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      # 3004 so that Aerospike can use 3000
      - "3004:3000"
    volumes:
      - ${PWD}/volumes/grafana/provisioning:/etc/grafana/provisioning
      - ${PWD}/volumes/grafana/dashboards:/var/lib/grafana/dashboards

  central-prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ${PWD}/volumes:/etc/prometheus
    ports:
      - "9091:9090"
    command:
      - "--config.file=/etc/prometheus/central-prometheus.yml"
      - "--web.enable-remote-write-receiver"  # Enable the remote write receiver
      - "--enable-feature=metadata-wal-records"