{
 "title": "Aerospike Vector Search",
 "description": "this dashboard displays key metrics related to vector search component including index, cache-size,  healer info etc.,",
 "tags": [
  "monitoring",
  "vector search"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_AEROSPIKE_PROMETHEUS", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job_name",
    "label": "Job",
    "query": {
     "query": "label_values(aerospike_vector_search_heartbeats_sent,job)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster Name",
    "query": {
     "query": "label_values(aerospike_vector_search_heartbeats_sent{job=\"$job_name\"},cluster_name)"
    }
   },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(aerospike_vector_search_heartbeats_sent{job=\"$job_name\", cluster_name=~\"$cluster|$^\"},instance)"
    }
   },
   {
    "name": "index",
    "label": "Index",
    "query": {
     "query": "label_values(aerospike_vector_search_requests{ job=\"$job_name\", cluster_name=~\"$cluster|$^\"},index)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(aerospike_vector_search_cluster_size{cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (cluster_name) (aerospike_vector_search_cluster_size{cluster_name=~\"$cluster\"})\n",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Index Vectors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (index) (aerospike_vector_search_requests{index=~\"$index\", type=~\"update\", update_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Index Queue size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (index) (aerospike_vector_search_indexing_queue_size{index=~\"$index\", type=~\"update\", update_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query (total)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (aerospike_vector_search_requests{index=~\"$index\", type=~\"query\", query_type=~\"client\",status=~\"success\",cluster_name=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Succes"
    },
    {
     "expr": "sum(aerospike_vector_search_requests{index=~\"$index\", type=\"query\", query_type=\"client\",status=\"error\",cluster_name=\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Cache Size (avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg (aerospike_vector_search_index_cache_size{index=~\"$index\", cluster_name=~\"$cluster\", instance=~\"$instance\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (status) (aerospike_vector_search_connections{cluster_name=~\"$cluster\"})",
       "legendFormat": "{{status}}"
      }
     ]
    },
    {
     "title": "Internal",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "sum by (status) (aerospike_vector_search_internal_connections{cluster_name=~\"$cluster\", instance=~\"$instance\"})",
       "legendFormat": "{{status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cache details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache Hit Ratio",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100* rate(aerospike_vector_search_index_cache_hits{cluster_name=\"$cluster\",index=\"$index\"}[40s])/(rate(aerospike_vector_search_index_cache_hits{cluster_name=\"$cluster\", index=\"$index\"}[40s]) + rate(aerospike_vector_search_index_cache_misses{cluster_name=\"$cluster\", index=\"$index\"}[$__rate_interval]) + 1)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cache Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_index_cache_size{cluster_name=\"$cluster\", index=\"$index\", } ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Cluster Size",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_cluster_size{cluster_name=\"$cluster\", } ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Indexed count",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_requests{type=\"update\", update_type=\"client\",status=\"success\",cluster_name=\"$cluster\", index=\"$index\" }",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Index details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Index Update Success (rate)",
     "type": "timeseries",
     "description": "Incoming vector queries successfully handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{index=\"$index\",type=\"update\", update_type=\"client\",status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Median Index Update Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_requests{index=\"$index\",type=\"update\", update_type=\"client\" ,quantile=\"0.5\",cluster_name=\"$cluster\", } * 1000 ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "In Memory Index Queue Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_indexing_queue_size{index=\"$index\",cluster_name=\"$cluster\", }",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Batch Merge (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_batch_merge{index=\"$index\",cluster_name=\"$cluster\", quantile=\"0.5\"}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Index Update Proxy-in (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"update\", index=\"$index\", update_type=\"proxy-in\", status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Index Update Local (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"update\", index=\"$index\", update_type=\"local\", status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Index Update Proxy-out (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"update\", index=\"$index\", update_type=\"proxy-out\", status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Index Update Error (rate)",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"update\", update_type=\"client\",status=\"error\",cluster_name=\"$cluster\", }[$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Query details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query Success (rate)",
     "type": "timeseries",
     "description": "Incoming vector queries successfully handled.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{cluster_name=\"aerospike-vector-search\",index=\"$index\", type=\"query\", query_type=\"client\",status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Median Query Time",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_requests{index=\"$index\",type=\"query\", query_type=\"client\" ,quantile=\"0.5\",cluster_name=\"$cluster\", } * 1000 ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Proxy-in (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"query\", index=\"$index\", query_type=\"proxy-in\", status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Proxy-out (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"query\", index=\"$index\", query_type=\"proxy-out\", status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Local (rate)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"query\", index=\"$index\", query_type=\"local\", status=\"success\",cluster_name=\"$cluster\", }[$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Query Error (rate)",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_requests{type=\"query\", query_type=\"client\",status=\"error\",cluster_name=\"$cluster\", }[$__rate_interval]) ",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Healer details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Healer Cycle Count",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_healer_cycle_count{cluster_name=\"$cluster\", index=\"$index\", type=\"cycle-time\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Healer Cycle Time",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_healer_cycle{cluster_name=\"$cluster\", index=\"$index\", quantile=\"0.5\", type=\"cycle-time\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Indexed Vector Record Count",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_vector_records{cluster_name=\"$cluster\", index=\"$index\", status=\"indexed\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Unindexed Vector Record Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 8, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_vector_records{cluster_name=\"$cluster\", index=\"$index\", status=\"unindexed\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "ReIndexed Vector Record Count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_vector_records{cluster_name=\"$cluster\", index=\"$index\", status=\"reindex\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Enqueue Index Out Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_healer_cycle_count{cluster_name=\"$cluster\", index=\"$index\", type=\"enqueue-index-out\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Enqueue Index In Count",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_healer_cycle{cluster_name=\"$cluster\", index=\"$index\", type=\"enqueue-index-in\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Enqueue Index Local Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "aerospike_vector_search_healer_cycle{cluster_name=\"$cluster\", index=\"$index\", type=\"enqueue-index-local\",}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Enqueue Index In Rate",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_healer_cycle{cluster_name=\"$cluster\", index=\"$index\", type=\"enqueue-index-in\",}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Enqueue Index Out Rate",
     "type": "timeseries",
     "description": "Incoming vector search query processing error.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_healer_cycle_count{cluster_name=\"$cluster\", index=\"$index\", type=\"enqueue-index-out\",}[40s])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Enqueue Local Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(aerospike_vector_search_healer_cycle{cluster_name=\"$cluster\", index=\"$index\", type=\"enqueue-index-local\",}[$__rate_interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}